simplr_install_intro:
    pattern:  /
    defaults: { _controller: CleentfaarSimplrCmsBundle:Install/Intro:index }

simplr_install_check:
    pattern:  /check
    defaults: { _controller: CleentfaarSimplrCmsBundle:Install/Check:index }

simplr_install_wizard_step1:
    pattern:  /wizard/step1
    defaults: { _controller: CleentfaarSimplrCmsBundle:Install/Wizard:step1 }

simplr_install_wizard_step2:
    pattern:  /wizard/step2
    defaults: { _controller: CleentfaarSimplrCmsBundle:Install/Wizard:step2 }