filter:
  paths:
    - 'src/*'

before_commands:
  # Copy parameters template for tests (db settings etc)
  - 'cp app/config/parameters.yml.dist app/config/parameters.yml'

  # Install packages, Scrutinizer already applies '--no-interaction' by itself
  - 'composer install'

tools:
  php_mess_detector: true
  php_code_sniffer:
    config:
      standard: 'PSR1'
  php_code_coverage:
    test_command: 'phpunit -c app'