filter:
  paths:
    - 'src/*'

before_commands:
  - 'composer install'

tools:
  php_code_sniffer:
    enabled: true
    config:
      standard: PSR2
  php_cs_fixer: true
  php_mess_detector:
    enabled: true
    config:
      code_size_rules:
        too_many_fields: false
        too_many_methods: false
      design_rules:
        coupling_between_objects: false
  php_analyzer: true
  sensiolabs_security_checker: true