language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - 'cp app/config/parameters.yml.dist app/config/parameters.yml'
  - 'composer self-update'
  - 'composer install -n --prefer-source'

script: phpunit -c app
