language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - "composer install -n"
  - "php app/console doctrine:database:create --env=test"
  - "php app/console simplr:assets:install --symlink --env=test"

script:
  - "phpunit -c app"
