parameters:
    simplr.pluginmanager.class: Simplr\PluggableBundle\Services\PluginManager
    simplr.thememanager.class: Simplr\PluggableBundle\Services\ThemeManager
    simplr.imagine_filter_loader.class: Simplr\ApplicationBundle\Imagine\Filter\Loader\SimplrLoader

services:
    simplr.pluginmanager:
        class: %simplr.pluginmanager.class%
        arguments: [%path_to_plugins%, @simplr.optionmanager]
    simplr.thememanager:
        class: %simplr.thememanager.class%
        arguments: [%path_to_themes%, @simplr.optionmanager]