imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            SimplrCore:
                type: annotation
                is_bundle: false
                dir: %kernel.root_dir%/../vendor/cleentfaar/simplr-core/src/Simplr/Core/Entity
                prefix: Simplr\Core\Entity
                alias: SimplrCore

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# Table prefix set-up
cleentfaar_doctrine_table_prefix:
    prefix: %table_prefix%

liip_imagine:
    #driver:               gd
    web_root:             %kernel.root_dir%/../web
    data_root:            %kernel.root_dir%/../web/assets/media
    cache_mkdir_mode:     0777
    cache_prefix:         /assets/media/cache
    #cache:                web_path
    #cache_clearer:        true
    #data_loader:          filesystem
    #controller_action:    liip_imagine.controller:filterAction
    #formats:              []
    #filter_sets:
    #    simplr_themes:
    #        filters:
    #            thumbnail: { size: [50, 50], mode: outbound }

#liip_imagine:
#    driver:               gd
#    web_root:             %kernel.root_dir%/../web
#    data_root:            %kernel.root_dir%/../web/assets/media
#    #data_root:           %liip_imagine.web_root%
#    cache_mkdir_mode:     0777
#    cache_prefix:         /assets/media/cache
#    cache:                web_path
#    cache_clearer:        true
#    data_loader:          filesystem
#    controller_action:    simplr.controller.images:filterAction
#    formats:              []
#    filter_sets:
#        resize:
#            path:         ''
#            filters:
#                simplr.imagine_filter_loader: { }