monolog:
    class: Silex\Provider\MonologServiceProvider
    parameters:
        monolog.logfile: "%path_to_logs%/app.log"
        monolog.level: 100
        monolog.name: app

twig:
    class: Silex\Provider\TwigServiceProvider
    parameters:
        twig.path: "%path_to_library%/Resources/views"