parameters:
    simplr.optionmanager.class: Simplr\ApplicationBundle\Services\OptionManager
    simplr.mediamanager.class: Simplr\ApplicationBundle\Services\MediaManager
    simplr.twig.simplr_extension.class: Simplr\ApplicationBundle\Twig\SimplrExtension
    simplr.entity.page.class: Simplr\ApplicationBundle\Entity\Page
    simplr.controller.pages.class: Simplr\ApplicationBundle\Controller\PagesController
    simplr.controller.images.class: Simplr\ApplicationBundle\Controller\ImagesController

services:
    simplr.optionmanager:
        class: %simplr.optionmanager.class%
        arguments: [@doctrine.orm.entity_manager]
    simplr.mediamanager:
        class: %simplr.mediamanager.class%
        arguments: [%path_to_media%, %uri_to_media%, @doctrine.orm.entity_manager]
    simplr.twig.simplr_extension:
        class: %simplr.twig.simplr_extension.class%
        arguments: [@service_container, @twig.loader]
        tags:
            - { name: twig.extension }
    simplr.repository.page:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine # this is an instance of Registry
        factory_method: getRepository
        arguments: [ %simplr.entity.page.class% ]
    simplr.controller.pages:
        class:     %simplr.controller.pages.class%
        arguments: [@templating, @simplr.repository.page]
    simplr.controller.images:
        class:     %simplr.controller.images.class%
        arguments: [@liip_imagine.data.manager, @liip_imagine.filter.manager, @liip_imagine.cache.manager]
    simplr.imagine_filter_loader:
        class: %simplr.imagine_filter_loader.class%
        tags:
            - { name: liip_imagine.filter.loader, loader: simplr.imagine_filter_loader }