parameters:
    simplr.optionmanager.class: Simplr\CmsBundle\Services\OptionManager
    simplr.imageresizer.class: Simplr\Core\Services\ImageResizer
    simplr.mediaurlgenerator.class: Simplr\Core\Services\MediaUrlGenerator
    simplr.mediamanager.class: Simplr\Core\Services\MediaManager
    simplr.twig.cms_extension.class: Simplr\CmsBundle\Twig\CmsExtension
    simplr.twig.pluggable_extension.class: Simplr\PluggableBundle\Twig\PluggableExtension
    simplr.entity.page.class: Simplr\CmsBundle\Entity\Page
    simplr.entity.media.class: Simplr\Core\Entity\Media
    simplr.controller.pages.class: Simplr\CmsBundle\Controller\PagesController
    simplr.controller.images.class: Simplr\CmsBundle\Controller\ImagesController

services:
    simplr.optionmanager:
        class: %simplr.optionmanager.class%
        arguments: [@doctrine.orm.entity_manager]
    simplr.mediamanager:
        class: %simplr.mediamanager.class%
        arguments: [@simplr.repository.media]
    simplr.imageresizer:
        class: %simplr.imageresizer.class%
        arguments: [{'alpha-resize-logo':{'dimensions':[100,200]}}]
    simplr.mediaurlgenerator:
        class: %simplr.mediaurlgenerator.class%
        arguments: [@request, @simplr.imageresizer, %path_to_media%, %uri_to_media%]
        scope: request
    simplr.twig.cms_extension:
        class: %simplr.twig.cms_extension.class%
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    simplr.twig.pluggable_extension:
        class: %simplr.twig.pluggable_extension.class%
        arguments: [@service_container, @twig.loader]
        tags:
            - { name: twig.extension }
    simplr.repository.page:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine # this is an instance of Registry
        factory_method: getRepository
        arguments: [ %simplr.entity.page.class% ]
    simplr.repository.media:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine # this is an instance of Registry
        factory_method: getRepository
        arguments: [ %simplr.entity.media.class% ]
    simplr.controller.pages:
        class:     %simplr.controller.pages.class%
        arguments: [@templating, @simplr.repository.page]
    simplr.controller.images:
        class:     %simplr.controller.images.class%
        arguments: [@templating, @simplr.repository.page]