simplr_install_welcome:
    pattern:  /welcome
    defaults: { _controller: CleentfaarSimplrCmsBundle:Install/Welcome:index }

simplr_install_check:
    pattern:  /check
    defaults: { _controller: CleentfaarSimplrCmsBundle:Install/Check:index }

simplr_install_check_run:
    pattern:  /check/run
    defaults: { _controller: CleentfaarSimplrCmsBundle:Install/Check:run }

simplr_install_update:
    pattern:  /update
    defaults: { _controller: CleentfaarSimplrCmsBundle:Install/Update:index }

simplr_install_update_run:
    pattern:  /update/run
    defaults: { _controller: CleentfaarSimplrCmsBundle:Install/Update:run }

simplr_install_about:
    pattern:  /about
    defaults: { _controller: CleentfaarSimplrCmsBundle:Install/About:index }

simplr_install_wizard:
    pattern:  /wizard
    defaults: { _controller: CleentfaarSimplrCmsBundle:Install/Wizard:index }

simplr_install_success:
    pattern:  /success
    defaults: { _controller: CleentfaarSimplrCmsBundle:Install/Success:index }
